### ISSUE TITLE
Doesn't work (at all)

### ISSUE THREAD

**Issue by qwertea** [MakeYourLifeEasier/novel-ebook.com#1]
Just a week or so ago it was working fine, but now clicking on Completed/Chinese/etc does nothing.

**Comment by qwertea** [comment]
Looks like api.allorigins.ml is refusing connection, I tried with a couple different VPN endpoints and browsers so I don't think it's on my end.

**Comment by Kurechii** [comment]
You are right. Its now working at all.

**Comment by MichaelGuardian** [comment]
Sry it took so long to respond to this ticket soemhow I didnt get any notifications.

The server that gets the chapters changed domains and thus the connection was refused. 

While the bug is resolved it seems that there are occasional probems with the server, failing to register a request which results in books not properly downloading. A fix for this issue will be released when the new user interface is ready.

Kind regards,

Michael
