### ISSUE TITLE
ESCAPE CODES not parsed correctly

### ISSUE THREAD

**Issue by Emasoft** [MakeYourLifeEasier/novel-ebook.com#237]
Lots of escape codes are not parsed correctly as characters, making the text hard to read.
This is Versatile Mage, chapter 1766, downloaded today:

``
Mo Fan&#x2019;s Demon Element.
It was dark and wet around him. The bottom of the cave was very spacious, and Mo Fan&#x2019;s vision in the dark was not too bad. He was able to see the rough appearance of the cave.
Cries of agony came from above him, followed by the sound of something slamming heavily to the ground.
&#x201C;That hurts&#x2026; my ass!&#x201D; A dark figure rose to his feet. His eyes were glittering faintly in the dark.
&#x201C;Zhou Donghao?&#x201D; Mo Fan recognized the idiot&#x2019;s voice.
&#x201C;It&#x2019;s me! So you think you can come down here, but I can&#x2019;t? You think only you care about Tao Jing? I care about her more than you!&#x201D; Zhou Donghao said righteously.
&#x201C;Are you retarded? Can you please lower your voice in a place like this? Or do you want to be smashed into pulp by the Rock Monsters?&#x201D; Mo Fan snarled.
&#x201C;I&#x2026;&#x201D; Zhou Donghao was lost for words.
``

**Comment by MichaelGuardian** [comment]
This is actually a problem with the new datasource, not with this application. There are some chapters/novels that seem to be affected by this issue but not all of them. While it is technically possible to retroactively go through the chapter content and fix it client-side, some early testing resulted in performance problems across low-end devices like smartphones. And since this fix would run for every chapter, not only the ones affected I'll decided against fixing this problem for now.
If I stumble across a solution for this problem in the future I'll implement a fix, but for now it probably would make more sense to look for a better datasource.
