### ISSUE TITLE
Can't download latest LOTR chapters

### ISSUE THREAD

**Issue by xenon205** [MakeYourLifeEasier/novel-ebook.com#5]
**Describe the bug**
Can't download latest LOTR chapters

**To Reproduce**
I chose two latest chapter from the list i pressed download.

![Bez tytułu](https://user-images.githubusercontent.com/14995106/60421961-31678b00-9beb-11e9-880b-f628bfff3a91.jpg)

**Comment by xenon205** [comment]
P.S. Do you have any paypal account or something. I would like to buy you a beer :)

**Comment by MichaelGuardian** [comment]
Thanks for the report!

Sadly, this bug is not caused by the webapp itself but by the external data source. While I can't fix it directly I will add a notice inside the finished e-book that explains why the chapters failed to download.

Glad you appreciate my litte side project, consider donating to the actuall authors and translators of the novels as their time commitment far outweights mine.

[But if you want to but me a beer nonetheless 🍺 ](paypal.me/9x2gDh39)

**Comment by MichaelGuardian** [comment]
Now there should be a notice if the chapter content is empty.
