### ISSUE TITLE
Please Change to better sources 

### ISSUE THREAD

**Issue by budikesuma** [MakeYourLifeEasier/novel-ebook.com#73]
Dear Devs.. 
you seem to take the source https://www.wuxiaworld.co/ (this site is known for many problems such as missing chapters, there are chapter titles but the contents are empty, messy chapters, there are chapter title bugs, etc.). 
There is a better site that is: https://novelfull.com/.  Please change immediately to a better source, thank you ..

**Comment by MichaelGuardian** [comment]
The problem with new sources is that it takes a significant amount of time to implement which I just don't have. Additionally it would also increase operating costs, which is a problem since I already pay out of my own pocket to keep the site running. I might do it in the future if I have a week or two of free time and if the user-base doubles.

**Comment by budikesuma** [comment]
Okay, that's great if you can make it happen in the future. Very thankful for your hard work.
