### ISSUE TITLE
Divine Throne of Primordial Blood not downloading properly

### ISSUE THREAD

**Issue by Janniik944** [MakeYourLifeEasier/novel-ebook.com#88]
Describe the bug
The download is basically picking out a couple of chapters here and there or copying them multiple times.
To Reproduce
You search for the novel, then you select your chapters and download. Depending on what you download the result will be different but all I tried where incomplete and chapters overall where missing or duplicated.

Desktop (please complete the following information):

Browser [Opera]

Smartphone (please complete the following information):

Device: [iPhoneXR]
OS: [e.g. iOS14]
Browser [safari]

**Comment by MichaelGuardian** [comment]
I think the problem is the sorting. Right now I'm not able to change the sorting without significant work. The chapters are ordered like they are shown in the download list, so if you would select everything it puts them in this order. Try downloading multiple epub files so that the ordering makes sense.
